### ISSUE TITLE
Connection flow and model: local TEE request first to TAM rather than TAM initiating a  device state query

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#10]
Dave Thaler raised the issue and recommended that the first request from a Client Application should start from requesting TEE to sign and then to TAM, not TAM to TEE.

"As I noted in my arch doc comments, I disagree that there needs to be any communication between the rich app being installed, and the TAM.  A valid implementation model should be that the app store installer reads the metadata (including TA dependencies) about the rich app, and as part of installing the rich app (without ever needing to run it), the installer can communicate with the TEE to express those dependencies, which then triggers the TEE to generate a signed message to the TAM, which can be related by the installer."

See also slide 3 and4: https://datatracker.ietf.org/doc/slides-102-teep-teep-hackathon-report/

**Comment by mingpeiwk** [comment]
Current architecture doc doesn't prescribe a TEE call flow. The protocol doc describes concrete TEE and TAM interaction flow for a TA installation. The update will go to the TEEP protocol doc.

**Comment by dthaler** [comment]
Closing issue against arch doc per WG discussion in Montreal where this issue was on the list to be closed.  Issues on other docs should be filed against those docs.
