### ISSUE TITLE
Key pair is burned into the TEE

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#108]
>    The TEE key pair and certificate are used for authenticating the TEE
>    to a remote TAM. Often, the key pair is burned into the TEE by the
>    TEE manufacturer and the key pair and its certificate are valid for
>    the expected lifetime of the TEE.

The term "burned into" gives me the impression that these keys are never changed. The security consideration section says something different. So, what are we trying to say?

**Comment by dthaler** [comment]
I read it as "Often" they're never changed, and sometimes they are.   Perhaps "Often" should be softened to "In some cases" to make to statement regarding how common it is?

**Comment by hannestschofenig** [comment]
I guess I shouldn't get hung up on this issue. I will close it.
