### ISSUE TITLE
Service Provider discussion is confusing

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#110]
Page 4 talks about "Service Providers (SP)", that intend to provide "services" through a TA, but never explains what this means, or what such 'services' refer to.   It's also confusingly similar to the term ISP so is unclear whether it's similar or different.

Section 4.6 then talks about the "App Developer" and even says "For the purpose of this document there is no difference between the SP and the app developer".

Since they are apparently synonymous, my reading is that the document would be far easier to read if the draft just use the term "App Developer" instead of "SP".

**Comment by mingpeiwk** [comment]
SP was originally used in OTrP, and we introduced use of "App Developer" at TEEP WG discussion, and considered them the interchangeable for use. I am good to use "App Developer" across the entire doc.
