### ISSUE TITLE
Text about carriers is confusing

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#112]
Several places in the doc use the term "carrier" without explaining why that's even relevant.   The roles defined were TAMs, device administrators, SPs (or app developers), etc., but not carriers so why are they relevant?

Also the "Multiple TAMs and Relationship to TAs" has text about "mobile devices" which also shouldn't appear except as an example, since many TEEs to which TEEP would apply are not in mobile devices.

**Comment by mingpeiwk** [comment]
The original target of the devices were largely mobile phones but other devices such as setup boxes and computer desktops are supported. Agreed to make "mobile devices" as examples, not the only device types in the text.

"network carrier" can be examples. It does play some role, for example, the "Device" definition in the Terminology section relates it with "Trust Anchor" as follows.

"This list is normally set by the Device Manufacturer, and may be governed by the Device's network carrier."

I think this may be updated to

"This list is normally set by the Device Manufacturer, and may be governed by the Device's network carrier when it is a mobile device."

On a related note, Trust Anchors for a TEE in a computer may not be always set by the "Device Manufacturer", and certainly nothing to do with a network carrier. Device Administrators will likely reset Trust Anchors.
