### ISSUE TITLE
Section 6.2.3 contradicts section 4.2

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#113]
Sec6ion 6.2.3 (Number of TEEP Brokers) implies there might only be one Broker even if there are multiple TEEs.  This contradicts section 4.2 which assumes one Broker per TEE.

In my reading of 6.2.3, I think all the text in that section is now obsolete (covered better by 4.2) and 6.2.3 can just be deleted.

**Comment by mingpeiwk** [comment]
Section 4.2 says that one TEEP Broker may manage one or multiple TEEs ("set of TEEs"). A device may have multiple TEEP Brokers. Quoted here:

"In these cases, the Rich Execution Environment hosts
   multiple TEEP brokers, where each Broker manages a particular TEE or
   set of TEEs."

Section 6.2.3 makes the topic more explicit. I think that we can compress that section and add a line to refer to 4.2 for TEE and TEEP Broker discussion.

I think we still want to recommend to have "one TEEP Broker" but allow multiple.

**Comment by dthaler** [comment]
PR 131 was merged, but need to discuss in the virtual interim whether that is sufficient or not, since still some discussion ongoing.
