### ISSUE TITLE
Figure 3 is too hard to understand

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#114]
Figure 3, and its discussion is really hard to follow and I think that figure needs a rewrite.

Some issues include:

- There's an "App Store" role in the header of the figure that isn't used, but should be (in 2a).
- Step 3 is illustrated as installing the Untrusted App from the TAM, which contradicts the text saying it's installed from the App Store.
- Text discussion says "The Untrusted Application will get messages from TAM" which is not true... the Broker does.
- The certs shown at the top of the diagram are not mentioned in the text discussion.
- I can't parse the sentence above the figure ("A device administrator may choose to accept a subset of the allowed TAs via consent or action of downloading.")

**Comment by mingpeiwk** [comment]
"App Store" is used where 2a should align with it. The '|' character was misplaced to the right which causes step 3 not right. It should be "App Store" to Device.

"A device administrator may choose to accept a subset of the allowed TAs via consent or action of downloading." - this line intends to mean that TA installation approval by an administrator may be explicit by consent or by implicit downloading. Some TAs may be accepted and some may be rejected by a Device Administrator.

Agreed to polish this paragraph. I will make the change.
