### ISSUE TITLE
Reference to IANA number

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#115]
Section 7.1 says "Standard TEE types are identified by an IANA number".

This should either be removed, or else a reference to a specific IANA registry should added.

**Comment by mingpeiwk** [comment]
Agreed. Standard TEE type names are not available today. I think we may need to add an IANA registry for this.

**Comment by dthaler** [comment]
If there is an IANA registry, that would presumably be mentioned in the document that needs to use the actual value, whether a TEEP Protocol spec, or an attestation claim spec, or whatever else.  I don't see anything in the arch doc itself that requires it so will remove mention from the arch doc.
