### ISSUE TITLE
Every Rich App Talks to TAM?

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#12]
Dave Thaler noted that the document seems to assume that every rich app that needs a TA, also needs to have code to talk to a TAM.

He states: 

  - I agree that's one possible implementation but the architecture should not require that.

  - An alternative implementation would be where the REE OS (e.g., the app store installer) contains code for communicating with TAM(s) using data in (for example) the rich app's manifest, and the rich app has no need to run until the TA is already installed. The installer/communicator is a rich app of a sort, but it's a different one from the client app that depends on the TA.

In his opinion, the arch doc should not require that it's the same app, but should certainly allow it to be.

**Comment by dthaler** [comment]
Addressed in draft -01
