### ISSUE TITLE
Is this still valid - one TA by multiple SPs

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#121]
Tiru raised this question:
   
 l) What is the use case for one TA and multiple SP ?

[Hannes] I am not sure.. I let Ming, DaveW, or DaveT respond.
[Dave] No idea, I’d propose deleting that section.   I was confused by it as well.

[MP] A TA software author can license the TA to multiple "buyers" who installs to their own user devices via their own TAM providers. The buyers are SPs in the original use case context. A TA developer doesn't necessarily distribute the TA. We have changed the meaning of SP to be interchangeable with an "App Developer" along with WG discussion, which treats the TA authorizer (SP) to devices as the owner of the TA.

A SP may provide its own "TA personalization data". Different SPs may provide different data. There needs a way to address the case when the same TA is installed to a device by multiple providers. To this end, the proposal was to have different "identifiers" for the TA to multiple SPs so that they don't have to be overwritten. A Device Administrator may decide which TAM and TA it allows to install to devices.

This is certainly a complex case, and not expected to be common in practice. Do you feel that we can disallow such a case where a TA author always directly works with a TAM service to distribute the TA? I feel that this licensed TA case may still have a place here.

**Comment by dthaler** [comment]
Issue #110 covered changing "service provider" to "TA app developer", which would make this issue about "one TA by multiple TA developers", where I suspect this question is actually about having the same TA binary signed by different signers.

Section 4.3 currently says:
```
   When a TA developer authors a TA, the TA itself is digitally signed,
   protecting its integrity, but the signature also links the TA back to
   the signer.  The signer is usually the TA developer, but in some
   cases may be another party that the TA developer trusts.  The TA
   developer selects one or more TAMs through which to offer their
   TA(s), and communicates the TA(s) to the TAM.
```

From Ming's answer I gather that the intent is that there could be multiple signers of the same original TA binary, and then each signer might select their own TAM.
