### ISSUE TITLE
Clarify code signing certificate type and where it is validated

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#122]
Tiru commented:
    [TR] What is need for self-signed certificates when code signing certificates by CA are used today ?
   In Figure 4, for the purpose of "Code signing" my understanding is the location of corresponding CA certs is both TEE and TAM.  

    [Hannes] I believe it would be useful to also store the CA cert that is used for code signing at the TAM because then it can verify the signed TAs.   

    I don’t believe there is any such requirement on a TAM.   It might be “useful” but is not required in my view.

[TR] why do you think verification in TAM is not required ?

[MP]  TA signature verification must be verified. Currently a TEE will check this code signing, and the CA certificate will be in TEE. See Figure 4 in the doc.

"Code Signing          1 per SP       TA binary          TEE"

Note the above "TA binary encryption" discussion. If a TA is given to a TAM in an encrypted form, such a signature check isn't feasible. But we can assume that TAM provider always vet TA binaries that it distributes for its service reputation protection.

Note that there is also the other TA delivery mode where a TA's binary is bundled inside an Untrusted Application as binary data. In this case, the binary isn't sent to TAM for distribution.

There is also the other case: many SPs / TA App Developers use the same extremely popular TAM service. Device manufacturers may want to limit to accept only a set of TA providers by using the code signing CA trust list. The architecture allows such support with the coding signing trust check in TEE.

    If we indeed believe the text in Section 9.1 is correct then that code signing CA cert also needs to be made available to the TEEP Broker and potentially even to the untrusted app.

[Dave]  I don’t believe the text in 9.1 is correct.

[MP] See above comment.

**Comment by dthaler** [comment]
I responded earlier on the thread saying "Sure.  Figure 4 talks about multiple certificates.   5.3 is a general statement about multiple types. 9.1 is about one specific type of cert that may or may not have a PKI. So they are not in contradiction but yes clarification would be good."
