### ISSUE TITLE
Add discussion about malicious TA removal

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#123]
Tiru commented:
   
 s) I have seen several malicious apps in App store in both Android and iOS, it is possible for an malicious App developer to publish both malicious untrusted applications  and malicious trusted applications.  I don't think the TEEP architecture prevents this attack and it is the responsibility of TAM and App store to remove such apps. See https://android-developers.googleblog.com/2018/01/how-we-fought-bad-apps-and-malicious.html.

[HT] Yes, it would be the responsibility of the TAM, the device manufacturer and the SP / developer to ensure that they do not distribute malicious TAs. It’s the responsibility of the TAM to not install malicious trusted apps, only authorized ones. I don’t think it’s correct to say it’s the responsibility of the TAM to “remove” malicious trusted apps, since it shouldn’t have installed it in the first place.
    The only case where “removal” might make sense is if the TAM previously authorized a trusted app, and later changed its policy that such TA is no longer authorized (e.g., because it was determined to be buggy or malicious or whatever else).
    
[TR] You may want to discuss the above case in the document.  If the trusted app is removed by TAM because it is malicious, some notification to the user would be helpful to remove the associated untrusted application in the REE.

[MP] Good suggestion. We may touch on this point in Security Consideration section too.

**Comment by dthaler** [comment]
Adding [TR] point about apps that start good and later versions turn malicious, as referred to in https://thenextweb.com/apps/2020/01/10/google-joker-malware-play-store/
