### ISSUE TITLE
Definition of "Untrusted Application" under Terminology is confusing

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#127]
The definition of "Untrusted Application" under Terminology does not read well.

**Currently:** 
_Untrusted Application: An application running in a Rich Execution Environment, such as an Android, Windows, or iOS application._

As it reads now, the statement defines an **untrusted application** as an application that is running in a Rich Execution Environment (REE). The statement next provides examples of REEs - "**Android**", "**Windows**"; and continues with an example of an application "**iOS application**". This set of examples is inconsistent and hence confusing.

**Suggested**
_Untrusted Application: An application running in a Rich Execution Environment, such as an Android, Windows, or iOS._

**Comment by mingpeiwk** [comment]
Agreed. Thanks Nicolae.

**Comment by dthaler** [comment]
This one was purely editorial... Commit 1ef2d840e98dffaf24a07488dd834aeb6c0e4243 just removes that phrase.  The longer explanation of example REEs is already under the REE definition.

Now reads:
_Untrusted Application: An application running in a Rich Execution Environment._
