### ISSUE TITLE
Path to TEEP for managment of connectivity, device managment, data managment subscription

### ISSUE THREAD

**Issue by 0Grit** [ietf-teep/architecture#128]
euicc should prove useful to provide embedded designs with IoT device services management as long as the MCU can mutually authenticate with the euicc.

Where does TEEP fit into this picture?

**Comment by dmwheel1** [comment]
Embedded UICC (eUICC) is a GSMA specification for remotely provisioning and reprovisioning profiles on the UICC (see https://www.gsma.com/aboutus/workinggroups/sim-working-group/embedded-sim). The benefit of the eUICC is to manage device profiles for communication providers without requiring physical replacement of SIM cards. This is expected to be beneficial for M2M/IoT devices.
TEEP is concerned with applications on devices, and managing the installation and configuration of applications within a device's TEE.
While these two areas both relate to secure provisioning/configuration they occur at different times in the lifecycle of the device, for different purposes, and (likely) by different instigators and supporting parties. 
TEEP is not intended to replace nor augment eUICC operations and does not depend on an UICC.
TEEP defines a set of identities and accompanying authentication credentials used to verify the device identity with the TAM and Service Provider. These identities and credentials must be under the control of the TEE, and have specific attributes/requirements but are defined in a platform-agnostic manner. 
One could imagine a specific implementation where these identities and credentials are contained within and managed by the eUICC on behalf of the TEE. In such a case these credentials could be used by TEEP via some TEE-to-eUICC interface. Such a design is a specific implementation and not a general architecture endorsed nor mandated by TEEP.
The TEEP authors view interaction with the eUICC / UICC to be an implementation-specific matter, and not something that must be (nor should be) addressed within the architecture specification.

If my answer does not address the core of your intended question, please feel free to restate your question, perhaps with more details and reference to other documentation/standards of which I may not be aware. I will leave the issue open for a few days to allow you to respond.  If this addresses your concern, please do let us know by commenting with a recommendation to close the issue.
