### ISSUE TITLE
TEEP Agent introduced prematurely and insufficiently introduced in the definition of TAM under System Components

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#129]
The (lengthy) definition of the Trusted Application Manager under "System Components" contains the following:

CURRENT TEXT:

"
(Statement 1) The TAM performs its management of TAs through an interaction with a device's TEEP Broker. (Statement 2) As shown in {{notionalarch}}, the TAM cannot directly contact a TEEP Agent, but must wait for the TEEP Broker to contact the TAM requesting a particular service. 
"

In the statement(s) above the TEEP Broker is introduced enough for the purpose of defining the TAM (statement 1). However, the TEEP Agent is neither minimally introduced nor defined earlier in the document; instead, it is first mentioned in a statement about the TAM _cannot_ do with it (2). That does not read well and is confusing for readers not already familiar with the architecture.

SUGGESTED CHANGE:
"
The TAM performs its management of TAs through an interaction with a device's TEEP Broker, that relays messages from the TAM to a TEEP Agent running inside the TEE. As shown in {{notionalarch}}, the TAM cannot directly contact a TEEP Agent, but must wait for the TEEP Broker to contact the TAM requesting a particular service. 
"

FURTHER SUGGESTIONS:

The definition of TAM under "System Components" is too long (_much_ longer than that of other components). Instead, I suggest that it is moved under a different section (e.g. Multiple TAMs and Relationship to TAs; in that case the section will need to be renamed though.)

**Comment by dthaler** [comment]
Accepted suggested text, with minor wordsmithing in PR #113 
Did not accept suggestion of moving TAM text to 4.3 since it must appear before the paragraphs near the end of 4.2.
