### ISSUE TITLE
Multiple TAMs for a single Client App

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#14]
Can a single Client Application be configured to talk to various TAMs? For example, if it requires multiple TAs could those be provided by different TAMs? For a single TA case is it possible that the Client App is able to select from which TAM it is provided, particularly when the TA is personalized (and potentially personalized differently by different TAMs). Should we make simplifications here?

**Comment by hannestschofenig** [comment]
DaveT believes that we should default to the simple case unless someone comes up with a convincing use case.

**Comment by mingpeiwk** [comment]
Note that this case is different from a case where the same TA binary can be distributed by two different TAMs.

**Comment by mingpeiwk** [comment]
A client may depend on two different TAs from two providers, e.g. a gaming app uses a payment TA and an authentication TA from two different partners.

**Comment by mingpeiwk** [comment]
TAM information is associated with a TA. Thus it is transparent to a client app whether it goes to one or two TAMs. It should follow the TAM destination that a TA manifest file indicates.

**Comment by dmwheel1** [comment]
See pull request #49

**Comment by dthaler** [comment]
Text needs to be updated.  It says "The TEEP Broker selects a single TAM that is consistent with the list of trusted TAMs (trust anchors) provisioned on the device."  
However, the choice is made by the TEEP Agent, not the TEEP Broker.   The TEEP Agent makes the choice based on its own policy, and inputs from the metadata mentioned in the text.  The Agent is free to override the info in the metadata based on its own policy (e.g., in a case where the device owner is in control of everything and there's only one TAM).   This is discussed in the transport spec, but is missing from this section of the arch spec.

**Comment by mpei1981** [comment]
With issue #64, we realize the limitation of single TAM for supporting end-to-end security between a device and SP. We change to allow multiple TAMs per client app, and actually further multiple alternative TAMs for a TA for better availability.

The limitation of single TAM is that a SP hosted TAM may not always want to aggregate other TAs that a client application depends on. There could be well known highly scalable TAMs for typical TAs. A SP will host its own TAM for TA binary and data that it doesn't want to share with a well known public TAM service. In this case, the SP would be forced to act as the single TA to collect all TAs if only a single TAM is supported. This was also raised during IETF WG discussion for a conflict with the resolution of issue #64.

A client can depend on multiple TAs. Each TA can be from a different TAM. These will be specified in a manifest file. TEEP Broker can reach to each TAM accordingly basing on manifest file.

A TEEP Broker can still talk with TEEP agent to verify which TAM is trustworthy for a TA before it directly reaches a TAM.

Furthermore, a TA binary can be carried by multiple TAMs, similar to application stores for client apps. We propose to allow multiple TAM URLs in a manifest file for a TA where it can be downloaded. Only one of the TAMs needs to be contacted and others can be used as failover TAM if the primary fails to respond.
