### ISSUE TITLE
Section 9.6 Malicious TA removal  - Possible contradiction with section 4.2

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#147]
Section 9.6 Malicious TA Removal mentions the following:

"
   It may happen that a TA was previously considered trustworthy but is
   later found to be buggy or compromised.  In this case, the TAM can
   initiate the removal of the TA by notifying devices to remove the TA
   (and potentially the REE or device owner to remove any Untrusted
   Application that depend on the TA).  If the TAM does not currently
   have a connection to the TEEP Agent on a device, such a notification
   would occur the next time connectivity does exist.
"
However, earlier in the document, Section 4.1 states that the TEEP Broker always initiates connection first:  

"As shown in Figure 1, the TAM cannot directly contact a TEEP Agent, but must wait for the TEEP Broker to contact the TAM requesting a particular service."

This leads to the following questions:

(1) Does the malicious/buggy TA keep running until the TEEP Broker requests contact with the TAM? (potentially a very long time?)

(2) Considering that the REE and TEEP Broker are both untrusted, what happens when they collude with the buggy/malicious TA?

**Comment by dthaler** [comment]
(1) Does the malicious/buggy TA keep running until the TEEP Broker requests contact with the TAM? (potentially a very long time?)

Answer: Yes, it might.

(2) Considering that the REE and TEEP Broker are both untrusted, what happens when they collude with the buggy/malicious TA?

That's why the last paragraph in the section is there:

> Furthermore the policy in the Verifier in an attestation process can be updated so that any evidence that includes the malicious TA would result in an attestation failure.

**Comment by mingpeiwk** [comment]
In the virtual interim meeting today, Michael raised a question how often should attestation be checked. This is a policy requirement to discuss. We agreed to file a separate issue to track this.

**Comment by dthaler** [comment]
My belief is that (given that #148 is being tracked separately) there's nothing needed in the document itself for this issue, since I believe it's covered by the text quoted earlier in this issue.   I do not believe there is any contradiction in the text.  Can we close this issue?

**Comment by nicopal** [comment]
+1
Since this topic is explored further in #148, I think this issue can be closed now.
