### ISSUE TITLE
TA attestation check frequency policy for compromised status check

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#148]
Related to the issue #147, attestation is one way to. check whether a TA has been compromised.
In the virtual interim TEEP meeting today, it is asked how often should the Attestation service should be checked. If we have a frequency as a policy, say, a TA attestation is valid for 1 week, or 1 month, who defines the policy: TAM that distributed the TA, or the TEEP agent in TEE or another entity that can define or update the policy.

**Comment by nicopal** [comment]
Regarding defining the policy duration - the TEEP agent in the TEE cannot be a good candidate for this since it requires that the TEE has a notion of time (i.e. has its own clock), which is not the case for e.g. Intel SGX.

**Comment by dthaler** [comment]
@nicopal Per the RATS architecture, Attestation is checked at a Verifier, and at a Relying Party (e.g., the TAM), so you are correct it's not the TEEP agent per se.

**Comment by mingpeiwk** [comment]
Just note that the question wasn't about how long an attestation result will be valid. The question is how often some entity reaches out a TA attestation service that the TA in the devices have not been compromised.

**Comment by mingpeiwk** [comment]
Some entity in the device is responsible to check whether TAs in the device are still healthy. It could cache the attestation result from the last call, and launch a new check upon expiration of that. Or it can use a policy period to periodically reach out an attestation Verifier. This looks to be a device policy that can be outside of TEEP. We talked that TAM may publish list of compromised TAs somewhere such that this entity of TA scanner in a device may reach out. Considering that any such an entity in REE could be compromised itself, there is no assurance that TA status scan can be carried out. Policy integration, if there is a period, for such an entity to follow, could not be assured to be honored. The bottom line exists in TEEP that a compromised TA will not pass attestation check in its next use when it is checked against the TAM that distributed it.

I think that we just recommend the best practice that an Untrusted Application or some system entity in REE may check TA status in its next use. This TA status check with a TAM hasn't been given an explicit API yet in TEEP protocol (other than Query, TrustedAppInstall and TrustedAppDelete). Additional specification would be needed for status validation if this is to be enforced.
