### ISSUE TITLE
Applicability of TPMs to TEEP

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#15]
TPMs have been mentioned in the past in discussions as a TEE technology that could make use of the TEEP functionality. It appears that their functionality today is too limited to have them in scope for TEEP. 

A discussion can be found here: https://www.ietf.org/mail-archive/web/teep/current/msg00357.html

**Comment by dmwheel1** [comment]
Agree. TPM does not run applications, so TEEP does not seem to apply to them.

**Comment by dthaler** [comment]
I checked with several TCG folks (at Microsoft and at STMicro) and they all said that TEEP need not mention TPMs.
