### ISSUE TITLE
Devices with no REE, which are mentioned in Section 4.1 of Draft06

### ISSUE THREAD

**Issue by kunisuzaki** [ietf-teep/architecture#150]
Devices with no REE are mentioned in Section 4.1 of Draft06.
"-  TEEP Broker:
....
In devices with no REE, the TEEP Broker would be absent and instead the TEEP protocol transport would be implemented inside the TEE itself."

If a device has no REE, there is no Untrusted Application. 
Why does the TEEP protocol need to support such a device?

I cannot mage the device which has no REE. 
I think the TEE just turns to be REE, and it is a normal device.

**Comment by dthaler** [comment]
> If a device has no REE, there is no Untrusted Application.

Correct.

> Why does the TEEP protocol need to support such a device?

Because it has a TEE that only allows authorized code in it, and that's what the TEEP protocol manages.

> I cannot mage the device which has no REE.

Others can.   An MCU with secure-boot, for example, can be implemented in such a way that the entire thing meets the definition of TEE stated in the document.

> I think the TEE just turns to be REE, and it is a normal device.

It doesn't, the definitions of TEE and REE are different.  For example, many commodity OS's allow arbitrary apps to be executed, which would certainly make them an REE and certainly not a TEE.   (Anything that lets someone copy an unsigned binary onto a system and execute it would not be a TEE.)

**Comment by dthaler** [comment]
This is related to previous issue #139 which the WG discussed in the Feb 10 TEEP virtual interim meeting, and which PR #145 addressed.

**Comment by kunisuzaki** [comment]
Excuse me, I cannot communicate directly at TEEP virtual meeting last night.
I still have questions. 
# Excuse me, I bother you.
My questions are  
“Q1) where is an Application which makes the first request for TEEP?" 
and 
"Q2) where is an Application which uses the TA installed by TEEP?”

----------------------------
Q1) The first request for TEEP comes from an Application to a TEEP Broker, and a TA is installed by TEEP protocol.
I am not sure how to create the first request from an Application if the device does not have REE.

Q2) In addition, TEEP doesn’t define “run or execution” of the TA. 
The “run or execution” is responsible for the Application.
It means that a TA is used by an Application. So, where is the Application?

The new draft (TEEP Architecture 8) assumes a microcontroller for no-REE and All code runs in the TEE. 
I guess TEEP works well, but there is no difference between Application and TA. 
In general, an Application is assumed to be un-secure but runs in TEE. 
I think it includes contradict.
Doesn't it ruin the assumption of TEE which protects from an un-secure Application?

**Comment by dthaler** [comment]
A1) The first request for TEEP does not need to come from an "application" per se.  See the RequestPolicyCheck abstract API in section 6.2.1 point 3.   This could be triggered by anything, including a boot loader of some sort.
A2) The document does not use the phrase "run or execution" that I can find.  "Run or execution" of a TA may or may not be the responsibility of an Application.  On SGX it is.  On TrustZone it is not.  On a microcontroller, I expect it would not be either.   So it is incorrect to assume that "a TA is used by an Application".

As for the third question "doesn't it ruin the assumption of TEE which protects from an un-secure Application": no, not all TEEs have that as the goal, or as the only goal.   Isolation between TAs means they also protect against one TA interfering with another TA.  Such isolation can also apply to TEEs with no-REE.

**Comment by dthaler** [comment]
Also regarding assumptions of TEEs, issue #158 and PR #159 also update the definition of a TEE slightly

**Comment by kunisuzaki** [comment]
Thank you for your quick reply, Dave.

1) OK. 
The entities which issue the first request of TEEP are not only Applications. The entities do not need to use the installed TA. The entities are just a trigger to install/update/delete of TA.

2) At first "Run or execution" is my original words. 
I was thinking TEEP is just a helper for TA installation/deletion for an Application. 
However, the entity to use TEEP is not Application only, as mentioned in 1).
I agree that some TAs are stealthy and independent of Applications and OS (For example, application-behavior-monitoring TA). TEEP can treat these TAs.
The real examples, which are independent of Applications, are “Pseudo Trusted Applications” and “Early TA” on OP-TEE, I think.
https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html
However, I am not sure they use TEEP to update/delete.

3) TEEP is just a protocol to install/update/delete a TA, and “Run or Execution” is out of scope.
In addition, the entity which uses TEEP does not need to run on REE. The entity can run on TEE.
**The entity, which runs on TEE and uses another TA, reminds me “Security Domain” which deleted from the previous draft. However, TEEP itself is available for “Security Domain”.**

**Comment by dthaler** [comment]
@kunisuzaki TEEP is a protocol to install/update/delete any code that runs in a TEE.  E.g., for OP-TEE based TEEs, it could even be used to update OP-TEE if the TEEP Agent (e.g., in a pseudo-TA) is implemented in a way to support that.

**Comment by kunisuzaki** [comment]
I agree that TEEP is a protocol to install/update/delete a code that runs in a TEE.
I am not sure TEEP covers all code in a TEE because TEEP architecture assumes some pre-defined entities in a TEE (Trust Anchors mentioned in Section 5, etc.).

Out of Scope items are (generally)
1) Who and How to use the code in a TEE
2) The data management used by the in a TEE
because they are matter of the code “in and out” a TEE.

In addition, TEEP is designed to cover the usages from cloud-server to IoT-micro-controller.
However, there are many types of TEEP implementations (ARM TrustZone on Cortex-A and Cortex-M, Intel SGX, AMD SVE, RISC-V Keystone, etc). 
I think it is tough work to put together these implementation differences in TEEP architecture.
I appreciate your effort.

**Comment by kunisuzaki** [comment]
Shall I close this issue?

**Comment by dthaler** [comment]
Sure.  I think we let either the filer or the chairs close issues, so if you close it, it's one less thing for the chairs to do. :)

**Comment by kunisuzaki** [comment]
O.K. I close this issue. Thank you.
