### ISSUE TITLE
I wonder if it is suitable for TEEP protocol to implement attestation using Remote Attestation of Intel SGX as below.

### ISSUE THREAD

**Issue by itohdaisuke** [ietf-teep/architecture#157]
There are three subjects;

1. Repeated QueryRequest - QueryResponse interactions in one attestation.
2. The EAT of QueryResponse has data for SGX Attestation.
3. The extensions of QueryRequest have data for SGX Attestation.

Each content is to be detailed in order. I hope you would read and may I have your opinion.

1. Repeated QueryRequest - QueryResponse interactions in one attestation.

For Remote Attestation of SGX to be put into practice, it is necessary to exchange messages between the TEEP Agent in a device and a TAM twice.
The following figure is from 'Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source'(https://download.01.org/intel-sgx/sgx-linux/2.7.1/docs/Intel_SGX_Developer_Reference_Linux_2.7.1_Open_Source.pdf, p.102).
![Intel_SGX_Developer_Reference_Linux_2_7_1_Open_Source_pdf（102___414ページ）-2](https://user-images.githubusercontent.com/62082278/76475150-5c280580-6441-11ea-8050-6c18e97bbb59.jpg)
(We can send msg0 with msg1 at step 10)

The connection is presented as ra_network_send_receive.
Corresponding to that, in terms of TEEP protocol it seems that exchanging QueryRequest and QueryResponse is to be done twice, doesn't it.

```
TAM                                         TEEP Agent
 Step1.QueryRequest ---------------------------->
 Step2.<----------------------------------------- QueryResponse(with EAT(msg0+msg1))
 Step3.QueryRequest(with Extention(msg2)) ------>
 Step4.<----------------------------------------- QueryResponse(with EAT(msg3))
GOOD or NG
```
(fig.1)

As summarized in fig.1, is it appropriate to implement the attestation of TEEP via repeated exchanges of QueryRequest and QueryResponse.

2. The EAT of QueryResponse has data for SGX Attestation.

At Step2 and Step4 in fig.1, the TEEP Agent ought to send to the TAM msg0, msg1, and msg3. Those are generated by the TEEP Agent and necessary for SGX Remote Attestation.

Is it correct to define custom claim identifier and send data packed in EAT of QueryResponse.

3. The extensions of QueryRequest has data for SGX Attestation.

At Step3 in fig.1, the TAM ought to send to the TEEP Agent msg2, which is generated by the TAM and necessary for SGX Remote Attestation.
Is it correct to define custom keys for the $$extensions part of QueryRequest and send data.

That is all.
With kind regards.

**Comment by itohdaisuke** [comment]
It seems that I should have asked this question in teep-protocol issues, not here.
I will do so. Could you close this issue. I apporogize for disturbing.

**Comment by dthaler** [comment]
Closing at filer's request
