### ISSUE TITLE
Terminology for "Agent"

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#16]
Both the architecture document as well as the OTrP specification use the term "Agent" to refer to an entity that relays the messages between the TAM and the TEE. It was proposed to use an alternative term instead and now we are searching for a suitable name. 

Here is the discussion: https://www.ietf.org/mail-archive/web/teep/current/msg00355.html

**Comment by dthaler** [comment]
During the WG meeting, the term with the most support at the time seemed to be "broker", if I recall correctly.

**Comment by hannestschofenig** [comment]
We settled on the term 'broker', which is the entity in the rich execution environment. Suggest that the issue gets closed.

**Comment by dthaler** [comment]
Done in draft-ietf-teep-architecture-01

**Comment by mingpeiwk** [comment]
This is further explicitly called out now in the architecture doc. TEEP Agent and TEEP Broker are both used for their respective roles. TEEP Broker runs in REE, and talks with its counterpart TEEP Agent inside a TEE. Done in draft-ietf-teep-architecture-03
