### ISSUE TITLE
Provide two examples to illustrate security operations and sensitive data by a TA in TEE

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#170]
Russ's review:

    1) Section 1 says:
       Typically, application components are chosen to execute inside a TEE
       because those application components perform security sensitive
       operations or operate on sensitive data.

Recognizing that this is the introduction, I was wondering if you could provide a bit more 
explanation here.  Earlier in the paragraph, the document offers an example of a banking 
application.  There would be components of such and application that are trusted, and other
 components would be untrusted. This concept is described, but the coupling to make a 
complete application could be more explicit to prepare the reader for the detail that is coming.
 Within such an application, it would be good to offer an example of a security sensitive 
operations and a separate example of operating on sensitive data.

**Comment by dthaler** [comment]
PR #162  is addressing this

**Comment by dthaler** [comment]
Fixed in draft-09
