### ISSUE TITLE
Revise the sentence  about the need of "an interoperable protocol"

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#171]
Russ:

>     2) Section 1 says:
>
>        To simplify the life of TA developers interacting with TAs in a TEE,
>        an interoperable protocol for managing TAs running in different TEEs
>        of various devices is needed.
>
>     This feels incomplete to me.  Making sure that compatible trusted and untrusted components of an application are installed on the same device is vital when they are not bundled.
>
>
> MP: how about the following?
>
>    To simplify the life of TA developers interacting with TAs in a TEE,
>    an interoperable protocol for managing TAs running in different TEEs
>    of various devices is needed in order for an untrusted application to use.

I think this is a big improvement.

**Comment by dthaler** [comment]
PR #163 is addressing this

**Comment by dthaler** [comment]
Fixed in draft-09
