### ISSUE TITLE
Application vs. Application component

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#172]
Russ commented:

>      4) Section 2 says:
>
>        -  Untrusted Application: An application running in a Rich Execution
>           Environment.
>
>     For alignment with the definition of a TA and te terms used in section 1, I think this should say:
>
>        -  Untrusted Application: An application component that runs in a
>           REE.
>
>     It is also useful to indicate that the Untrusted Application may be dependent on one or more TAs.
>
>
> MP: Agree on the additional line. Not sure about changing "application" to "component". An untrusted application intends to mean a regular client application. Trusted application is an independent application; we don't require that the two are strongly tied. Multiple untrusted applications can call the same trusted application.

Russ: A TA is an "application component", so the Untrusted Application is also an "application component", right?  If not pick another term for both definitions.

**Comment by mingpeiwk** [comment]
Agreed with Russ to use "application" in both places for consistency.

**Comment by dthaler** [comment]
Fixed in draft -10
