### ISSUE TITLE
Revise definition of "CA"

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#173]
Russ commented:

>      7) Section 4.1 defines CA incorrectly.  A CA is not "Certificate-based credentials".  A CA issues certificates, and the certificates are then used for authentication and cryptographic key management.  This bullet should begin: "A CA is ..." to follow the pattern of the other bullets.
>
>
> MP: how about the following changes?
>
> Certification Authority (CA): Certificate-based credentials used
>       for authenticating a device, a TAM and a TA developer.
>
> To
>
> Certification Authority (CA): A CA issues certificates that can be used
>       for authenticating a device, a TAM or a TA developer. Different CAs
>       may be used for issuing certificates for a device, a TAM and a TA developer.

That seems fine.

**Comment by mingpeiwk** [comment]
Fixed by #165

**Comment by dthaler** [comment]
Fixed in draft-09
