### ISSUE TITLE
Use one term among "TA software author", "TA binary signer", and "TA signer."

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#174]
Russ commented:

     8) Section 4.3 introduces the term "TA software author" and "TA signer."  I hope we ca pick one.  Please add the term that is chosen to Section 2.

MP: prefer to pick "TA signer". Will add definition to Section 2.

**Comment by dthaler** [comment]
I disagree that these are the same.   There are two (not 1 or 3) concepts: TA software author, and TA (binary) signer.   Often the TA software and TA signer are the same entity, but that is not always the case.   That's the whole discussion of countersigning (or even replacing the signature) with a key the TEE or TEEP Agent will trust.

**Comment by dthaler** [comment]
The document already has this text:

> The signer is usually the TA developer, but in some cases might be another party that the TA developer trusts, or a party to whom the code has been licensed (in which case the same code might be signed by multiple licensees and distributed as if it were different TAs).

So "TA software author" and "TA developer" are the same (and we should use one term for that),
but that's a separate term from "TA signer" and "TA binary signer" (and we should use one term for that).

**Comment by dthaler** [comment]
Looks like PR #161 was addressing this

**Comment by dthaler** [comment]
Looks like PR #165 is addressing this

**Comment by dthaler** [comment]
However, I disagree with the changes in PR #165, so I do not believe this has been (correctly) addressed yet

**Comment by dthaler** [comment]
Fixed in draft -10
