### ISSUE TITLE
Add integrity protection in section 4.4

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#175]
Russ commented:

     9) Section 4.4 should require support for both confidentiality and integrity protection.

MP: it currently says 

   "Implementations must support
   encryption of personalization data to preserve the confidentiality of
   potentially sensitive data contained within it."

Agreed. We should add integration protection support too. How about the following?

   "Implementations must support
   encryption of personalization data to preserve the confidentiality of
   potentially sensitive data contained within it and support integrity protection."

**Comment by dthaler** [comment]
Fixed in draft-09
