### ISSUE TITLE
Add GP TEE example in section 4.4.1

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#176]
Russ commented:

>      10) Should GlobalPlatform be added to Section 4.4.1?
>
>
> MP: GP TEE can be referred to in the TrustZone section. How about the following?
>
> "A TA is loaded by a trusted OS running in the TEE such as a GlobalPlatform compliant TEE,"

This section has a paragraph about ARM and Intel TEEs.  Elsewhere the document talks about GlobalPlatform.  I think it should get a paragraph too so that the reader can compare and contrast the three TEEs.

**Comment by dthaler** [comment]
My opinion: would accept contributed text, but I don't think it's required.  We should not try to enumerate all TEE implementations.

**Comment by mingpeiwk** [comment]
>> I think it should get a paragraph too so that the reader can compare and contrast the three TEEs.
I think that the GP TEE on top of TrustZone can be covered in the ARM TrustZone section. The illustration in the Arm TrustZone section largely applies to a GP TEE.

Hope this can satisfy Russ's ask.
