### ISSUE TITLE
Section 5 wording about key transport and key agreement

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#177]
Russ commented:

12) Section 5 says: "... encrypted with the TAM public key ...".  This is not correct.  The TAM public key is used to establish the key that is then used for encryption and decryption.  Further the wording is aimed at RSA, which is a key transport algorithm.  Please make the wording accommodate key transport and key agreement approaches.

**Comment by dthaler** [comment]
PR #166 started addressing this, but it still needs work.

**Comment by dthaler** [comment]
Fixed in PR #166

**Comment by dthaler** [comment]
Fixed in draft -10
