### ISSUE TITLE
Section 5.1 - use of a raw public key in TAM?

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#178]
Russ commented:

>      13) Section 5.1 says that a TAM obtains "a TAM certificate from a CA"; however, Section 1 said that a trust anchor could be a raw public key..  Can the TAM use the raw trust anchor key directly?
>
>
> MP: It isn't a common case to use a fixed public key as a trusted anchor instead of a CA certificate. How about allowing a TAM to use a self-signed certificate? It accommodates both.

That does not align with the discussion of what a trust anchor is in RFC 5280.  I think the raw key needs to be allowed, even it if is not the most popular choice in current implementations.  For example, TLS did not originally allow raw public keys, but it was added later.  Here, all of the foundational specifications already allow it, so I do not think it is wise to prohibit raw public keys.

**Comment by dthaler** [comment]
PR #166 is addressing this

**Comment by dthaler** [comment]
Fixed in PR #166

**Comment by dthaler** [comment]
Fixed in draft -10

**Comment by tireddy2** [comment]
I don't see any use of the term RPK in the document.

**Comment by dthaler** [comment]
The abbreviation RPK wasn't used, only the full term "raw public key" (or sometimes just "public key").  Will remove acronym RPK

**Comment by dthaler** [comment]
Done in draft -12
