### ISSUE TITLE
Section 7 - clarify different attestation algorithms

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#179]
Russ commented:

     16) Section 7 says that there are "different attestation algorithms".  Does this mean different set of claims?  Please be more clear here.

MP: it currently means algorithm agility and algorithms may be different for different devices. Different set of claims from different algorithms from one device is possible but not necessary, I think. A verifier is expected to support all the supported algorithms such that it doesn't have to require different claims to get one working.

We will clarify the text.

**Comment by dthaler** [comment]
See PR #167

**Comment by dthaler** [comment]
Fixed in draft-09
