### ISSUE TITLE
Section 5.2 and 5.3 - allow signatures to be directly by the trust anchor

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#180]
Russ commented:

>      14) Section 5.2 and Section 5.3 should allow signatures to be directly by the trust anchor.  The current working requires a certification path.
>
>
> MP: we assume that signer and the intermediate CAs up to the trust anchor but not include a trust anchor are sent in a signature payload. This can establish a certificate path. Do you mean this about "directly by the trust anchor"? We need to allow intermediate CAs. We can revise the paragraph to elaborate on this if you agree..

No.  Please look at RFC 5934.  Signatures are verified by the trust anchor itself or by the public key in a certificate that validates to the trust anchor.

**Comment by dthaler** [comment]
PR #166 is intended to address this

**Comment by dthaler** [comment]
Fixed in PR #166

**Comment by dthaler** [comment]
Fixed in draft -10
