### ISSUE TITLE
Section 9.7 - add a sentence for making a device certificate that never expires

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#183]
Russ:

    Section 9.7: You may want to point to Section 4.1.2.5 of RFC 5280, which tells how to make a device certificate that never expires.

MP: will add a sentence to indicate this possibility.

"

TEE device certificates are expected to be long lived, longer than
   the lifetime of a device."

==>

"TEE device certificates are expected to be long lived, longer than
   the lifetime of a device. They can be certificates that never expire 
   as defined in the Section 4.1.2.5 of RFC 5280."

**Comment by dthaler** [comment]
See PR #168

**Comment by dthaler** [comment]
Fixed in draft-09

**Comment by tireddy2** [comment]
For those cases where TEE devices are given certificates for which no good expiration date can be assigned the recommendations in
Section 4.1.2.5 of RFC 5280 [RFC5280] are applicable.

Nit> Remove duplicate RFC5280

**Comment by dthaler** [comment]
Done in draft -12
