### ISSUE TITLE
Discussion to cover compromised trust anchors and compromised intermediate CAs.

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#185]
Russ commented:

19) Section 9.4: Please expand this discussion to cover compromised trust anchors and compromised intermediate CAs.

**Comment by dthaler** [comment]
Fixed in draft-09

**Comment by tireddy2** [comment]
You may also want to discuss expiry of root certificates.

**Comment by dthaler** [comment]
Done in draft -12
