### ISSUE TITLE
[Hackathon] How does Agent get unneeded TA list

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#213]
This issue was found during the Hackathon while implementing the TEEP protocol.

https://tools.ietf.org/html/draft-ietf-teep-architecture-13#section-6.2.1 has:

```
6.2.1.  TEEP Broker APIs

   The following conceptual APIs exist from a TEEP Broker to a TEEP
   Agent:

   1.  RequestTA: A notification from an REE application (e.g., an
       installer, or an Untrusted Application) that it depends on a
       given Trusted Component, which may or may not already be
       installed in the TEE.
```

However there is no "UnrequestTA" conceptual API, so the TEEP Agent would have no way to know when any such dependencies from Untrusted Applications were removed (e.g., due to the Untrusted Apps being uninstalled).

Per IETF 108 discussion, the TEEP protocol has a way to tell the TAM which TA's are no longer needed so the TAM can choose whether to remove them.  But there's no way specified for the Agent to get such information without a conceptual API like this.

Corresponding issues on the other specs:
* Transport spec: https://github.com/ietf-teep/otrp-over-http/issues/30
* Protocol spec: https://github.com/ietf-teep/teep-protocol/issues/81

**Comment by mcd500** [comment]
@mingpeiwk Can we merge the PR https://github.com/ietf-teep/architecture/pull/216 addresses this issue?

**Comment by dthaler** [comment]
Fixed in draft -14
