### ISSUE TITLE
TEE OS

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#220]
Russ Housley writes:

> This revision seems to introduce a new term in Section 4.4.2: "TEE OS".  It only appears once, so I would prefer to see this reworded to not create this term.  I suggest the phrase instead: "A trusted OS running in the TEE".  I believe this phrase has the same meaning.

**Comment by mingpeiwk** [comment]
Agree the change.

**Comment by dthaler** [comment]
Fixed in draft -15
