### ISSUE TITLE
Indicate the possibility to terminate TLS in the TEE

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#222]
6.2.  TEEP Broker Implementation Consideration

[...]

<mglt>

>                            Model:    A      B      C     ...
> 
>                                     TEE    TEE    TEE
>         +----------------+           |      |      |
>         |      TEEP      |     Agent |      |      | Agent
>         | implementation |           |      |      |
>         +----------------+           v      |      |
>                  |                          |      |
>         +----------------+           ^      |      |
>         |    TEEP/HTTP   |    Broker |      |      |
>         | implementation |           |      |      |
>         +----------------+           |      v      |
>                  |                   |             |
>         +----------------+           |      ^      |
>         |      HTTP      |           |      |      |
>         | implementation |           |      |      |
>         +----------------+           |      |      v
>                  |                   |      |
>         +----------------+           |      |      ^
>         |   TCP or QUIC  |           |      |      | Broker
>         | implementation |           |      |      |
>         +----------------+           |      |      |
>                                     REE    REE    REE
> 
>                        Figure 5: TEEP Broker Models

I am wondering if TLS could be included
into the TEE.  It is correct that I do
not envision TCP being in the TEE. 

[Hannes] This can be done and is done regularly. I think we should update the figure to include this option since it is very common.

**Comment by dthaler** [comment]
It's model C.   Simplest change would be to change "HTTP" to "HTTP(S)".  Also keep in mind that these are just examples.

**Comment by dthaler** [comment]
Fixed in draft -15
