### ISSUE TITLE
Insufficient description for compromised TAM

### ISSUE THREAD

**Issue by bremoran** [ietf-teep/architecture#241]
https://github.com/ietf-teep/architecture/blob/master/draft-ietf-teep-architecture.md?plain=1#L1326

I'm very concerned that this is not an adequate description of the requirements for validating a TAM. A verification of certificates is inadequate to deal with an Advanced Persistent Threat against a TAM and the consequences are significant. I'd be happy to suggest some additional text.

**Comment by dthaler** [comment]
@bremoran Can you suggest some additional text?
