### ISSUE TITLE
Paul Kyzivat GENART review

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/architecture#248]
https://datatracker.ietf.org/doc/review-ietf-teep-architecture-16-genart-lc-kyzivat-2022-04-04/

1) MINOR: Section 4.5, Fig 3

I find this figure confusing. It starts out looking like a sequence 
diagram, where time flows from top to bottom. But then overlayed on it 
is a nested text outline that seems to interact with the sequence 
diagram. Based on the outline numbering I expect the time sequence to be 
2a,2b,3,4. but based on positioning within the sequence diagram it seems 
that the order should be 2a,3,2b,4. I don't understand how this is 
intended to be read.

2) MINOR: Section 6.2.1:

Is any persistent state assumed in this API or is it stateless? If state 
is assumed, I would like to see the state model described.

3) NIT: Section 1: NIT

    TEEs use hardware enforcement combined with software protection to
    secure TAs and its data.

s/its/their/

4) NIT: Section 2: Device User:...

The last sentence is a fragment. Needs to be reworded.

5) NIT: IdNits

IdNits reports a couple of outdated references that need updating.

**Comment by mingpeiwk** [comment]
1. Modified the diagram to show the flow 2a, 2b, 3 and 4 that was expected.
2. Stateless. Any state is carried in the messages of request and response all the time.
3. Fixed
4. Fixed - the segmented words are removed, which were not supposed to be there.

See PR #252
