### ISSUE TITLE
Lars Eggert GEN-AD Review

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#253]
https://mailarchive.ietf.org/arch/msg/teep/bV6hUjuyOZrukfWLhG2NDtj2Y5c/

# GEN AD review of draft-ietf-teep-architecture-18

CC @larseggert

Thanks to Paul Kyzivat for the General Area Review Team (Gen-ART) review
(https://mailarchive.ietf.org/arch/msg/gen-art/_PQLgwbAxaVsfWgfg62QZHYYlYs).

### Unclear consensus

The datatracker state does not indicate whether the consensus boilerplate
should be included in this document. The shepherd writeup makes it pretty
clear that it should, so please change the datatracker metadata for the
document?

### Inclusive language

Found terminology that should be reviewed for inclusivity; see
https://www.rfc-editor.org/part2/#inclusive_language for background and more
guidance:

 * Term `man`; alternatives might be `individual`, `people`, `person`
 * Terms `she` and `he`; alternatives might be `they`, `them`, `their`

## Nits

All comments below are about very minor potential issues that you may choose to
address in some way - or ignore - as you see fit. Some were flagged by
automated tools (via https://github.com/larseggert/ietf-reviewtool), so there
will likely be some false positives. There is no need to let me know what you
did with these suggestions.

#### Section 4.1, paragraph 4
```
-       Administators may elect to use a TAM for remote administration of
+       Administrators may elect to use a TAM for remote administration of
+               +
```

#### Section 4.1, paragraph 5
```
-       Trusted Component Signers or Device Administators to use the TAM's
+       Trusted Component Signers or Device Administrators to use the TAM's
+                                                   +
```

#### Section 4.4.2, paragraph 1
```
-    a specific Untrused Application process lifetime as occurs in SGX.  A
+    a specific Untrusted Application process lifetime as occurs in SGX.  A
+                     +
```

#### Section 4.5, paragraph 8
```
-    via a TEEP Broker that faciliates communications between the TAM and
+    via a TEEP Broker that facilitates communications between the TAM and
+                                 +
```

### Boilerplate

Document still refers to the "Simplified BSD License", which was corrected in
the TLP on September 21, 2021. It should instead refer to the "Revised BSD
License".

#### Section 2, paragraph 8
```
ust resist modification against unauthorized insertion, deletion, and modifi
                                ^^^^^^^^^^^^
```
Do not mix variants of the same word ("unauthorized" and "unauthorised") within
a single text.

#### Section 4.5, paragraph 9
```
ed further in Section 5.3 below. Typically the same key TEE pair is used for
                                 ^^^^^^^^^
```
A comma may be missing after the conjunctive/linking adverb "Typically".

#### Section 6.1, paragraph 1
```
. ProcessTeepMessage: A message arriving on an existing TEEP session, to be d
                                ^^^^^^^^^^^
```
The usual preposition after "arriving" is "at", not "on". Did you mean
"arriving at"?

#### Section 7, paragraph 1
```
s, from trusted app updates for smart phones and tablets to updates of code
                                ^^^^^^^^^^^^
```
Nowadays, it's more common to write this as one word.

#### Section 9.1, paragraph 3
```
AM certificates might get compromised or its certificate might expire, or a T
                                     ^^^
```
Use a comma before "or" if it connects two independent clauses (unless they are
closely connected and short).

#### Section 9.1, paragraph 4
```
EE certificates might get compromised or its certificate might expire, or a T
                                     ^^^
```
Use a comma before "or" if it connects two independent clauses (unless they are
closely connected and short).

#### Section 9.3, paragraph 1
```
oked by a timer or other event. Furthermore the policy in the Verifier in an
                                ^^^^^^^^^^^
```
A comma may be missing after the conjunctive/linking adverb "Furthermore".

#### Section 9.3, paragraph 3
```
 certificates are expected to be long lived, longer than the lifetime of a d
                                 ^^^^^^^^^^
```
This word is normally spelled with a hyphen.

## Notes

**Comment by mingpeiwk** [comment]
Fixed in PR #257

**Comment by mingpeiwk** [comment]
On "BSD License" comment, it looks that our last revision already use "Revised BSD License":


"Code Components extracted from this document must include Revised BSD License text as described in Section 4.e of the Trust Legal Provisions and are provided without warranty as described in the Revised BSD License."

**Comment by mingpeiwk** [comment]
@hannestschofenig @dthaler could you help on adding "consensus boilerplate"? Thanks.

**Comment by larseggert** [comment]
The "boilerplate" thing is a state a chair needs to set in the datatracker.
