### ISSUE TITLE
Device administrator vs Device owner

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#29]
The definition of "Device Administrator" (p.6)  mentions that "A device owner can manage the list of allowed TAMs by modifying the list of Trust Anchors on the Device.".

The device owner is neither defined nor mentioned elsewhere in the document; therefore, it should either be turned into 'device administrator' or defined.

**Comment by dthaler** [comment]
-01 still has "A device owner can
      manage the list of allowed TAMs by modifying the list of Trust
      Anchors on the Device."

**Comment by hannestschofenig** [comment]
From IETF #103 
Issue #29 Device Admin vs Device Owner; almost ready to close, though there was a
further suggestions of defining three roles:
    - device owner (sets policy defining what can be done with the device)
    - device admin (executes/?enforces that policy)
    - device operator
Simpler update is to replace all instances of “device owner” to “device admin”. This
issue remains open until the updates are made.

**Comment by mingpeiwk** [comment]
Suggest add a clarification that a "device admin" for a corp device isn't necessarily the "device user" who uses the device.

**Comment by dmwheel1** [comment]
This should now be closed.  Hannes and/or Ming, please verify you are OK with changes and agree this issue is closed.

**Comment by mingpeiwk** [comment]
Agreed to close it after reviewing the changes in the draft.
