### ISSUE TITLE
Cardinality of TEE key pair and certificate

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#30]
In Section 5.6 Keys and Certificate Types, §2 TEE Key pair and certificate (p. 17):

The cardinality of TEE key pair and certificate is currently 'one per device'.
However, according to the 'Scope and Assumptions', "This specification assumes that an applicable device is equipped with one or more TEEs"

**Therefore, for devices with multiple TEEs, it could make sense to change the cardinality of TEE key pair and certificate to "one per TEE".**

Otherwise, in an example where two installed TEEs are produced by different manufacturers (unlikely, but potentially possible?), the two manufacturers would have to agree on how to produce a shared keypair/certificate.

**Comment by hannestschofenig** [comment]
I agree that the use of multiple TEEs requires the cardinality of the keys to be changed. This part has not been taken into account yet in the draft updated. Thanks for spotting this oversight.

**Comment by hannestschofenig** [comment]
Relates to issue #14

**Comment by dthaler** [comment]
@ncamwing this was addressed in pull request #76 and is now ready to be closed
