### ISSUE TITLE
Seed for TAM protocol

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#31]
Section 7.1 Attestation Hierarchy mentions that "seed required for TAM protocol operation must be built into the device at manufacture". 

This is technically correct, but considering that the architecture assumes the presence of multiple TEEs on the device, it could be rephrased as "seed required for TAM protocol operation must be built into the **TEE** at manufacture".

**Comment by hannestschofenig** [comment]
I looked into the text and I wonder whether we really need to talk about the seed in the architecture document. To me it sounds like providing a bit too much details about the OTrP protocol in the architecture draft. Hence, I am proposing to remove the seed concept from the architecture document to resolve this comment.

**Comment by hannestschofenig** [comment]
Section 7.1 should briefly talk about what attestation in the context of TEEP is and what we are trying to accomplish.

**Comment by hannestschofenig** [comment]
Related to issue #17

**Comment by mingpeiwk** [comment]
This will be addressed in attestation discussion update in the draft. Seeding of attestation keys will be discussed where seeding at manufacture becomes one of the ways, not the only way. The overall trust of attestation claims will have a list of assumptions for an attestation key to be trusted.
