### ISSUE TITLE
Figure one arrow directionality correct?

### ISSUE THREAD

**Issue by ncamwing** [ietf-teep/architecture#36]
The architectural diagram appropriate shows the TEEP Broker being the initiator to communicate with the TAM; however, is it the case that the TEEP Broker is the initiator to communicate with the TEE?

The question asked by our notetaker RW: in the diagram, Dave W said any comms between the device and a TAM is initiated by the device (not the TAM). Is that implicit, in the diagram, in the unidirectional arrow from the device (specifically, the TEEP Broker) to the TAM? If so, do the unidirectional arrows between other components in the diagram represent the same implicit rule (i.e. that the origin of the arrow denotes the element that always initiates communication)?

**Comment by hannestschofenig** [comment]
Related to issue #39

**Comment by hannestschofenig** [comment]
From IETF#103:

Robin W asks (in the notes so as to not interrupt note taking) : in the diagram, Dave W
said any comms between the device and a TAM is initiated by the device (not the
TAM). Is that implicit, in the diagram, in the unidirectional arrow from the device
(specifically, the TEEP Broker) to the TAM? If so, do the unidirectional arrows between
other components in the diagram represent the same implicit rule (i.e. that the origin of
the arrow denotes the element that always initiates communication)?
Nancy CW: Yes, that is the intent. Although, we should confirm this with the authors,
so we can open an issue to track this.

**Comment by mingpeiwk** [comment]
We have reviewed the arrow directions in the latest updated architecture diagrams, and can confirm that it conforms what we intended in representing the communication origin.
