### ISSUE TITLE
Messed up example in Section 5.12 "A Sample Device Setup Flow" 

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#37]
In the translation from XML to Markdown the text describing the example in Section 5.12.  A Sample Device Setup Flow got messed up. Text may have gotten lost as well.

**Comment by mingpeiwk** [comment]
Fixed the format. No text was lost. Just some typo in markdown format list symbols.

**Comment by hannestschofenig** [comment]
Addressed with pull request #41 - https://github.com/ietf-teep/architecture/pull/41

**Comment by mingpeiwk** [comment]
Shall we close this as we do after updates of draft?

**Comment by dthaler** [comment]
Verified ok in draft -03
