### ISSUE TITLE
trust anchor fingerprint

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#38]
From IETF#103:

v01 now includes text to define and distinguish between
- Trust Anchor
- Root of Trust
Eric Norrmark: over the course of the device lifecycle, there are times when more than
one trust anchor will be present (for example, when transitioning from one trust anchor
to its replacement). Follow-up question: does the architecture define any mechanism
other than an expiry date in a certificate, to indicate when a trust anchor should be
replaced.
Russ H: suggests adding text to define 'trust anchor fingerprint' and its role as part of
the validation/replacement process for trust anchors.
Nancy C-W where would this term be used in the documentation as a whole?
Dave T: rather than add as a discrete term definition, append this text to the definition
of 'trust anchor'.
General “nod’ from the participants in the room

**Comment by hannestschofenig** [comment]
Relates to issue #32

**Comment by mingpeiwk** [comment]
Updated architecture doc section for the definition of "Trust Anchor" to reflect the following.

- Trust Anchor fingerprint can be stored as part of Trust Anchor for unique identification
- It should be checked and used in Trust Anchor management to uniquely identify the right one.

See draft update on this.

Note a reference that RFC6024 talks about "Trust Anchor Management". It defines a Trust Anchor Format about what it should contain.

**Comment by hannestschofenig** [comment]
Addressed with pull request #40 - https://github.com/ietf-teep/architecture/pull/40

**Comment by mingpeiwk** [comment]
Quoted the updated definition of Trust Anchor here.

"Trust Anchor: A public key in a device whose corresponding private
    key is held by an entity implicitly trusted by the device. The
    Trust Anchor may be a certificate or it may be a raw public key
    along with additional data if necessary such as its public key
    algorithm and parameters.
    The Trust Anchor is normally stored in a location that resists
    unauthorized modification, insertion, or replacement. The digital
    fingerprint of a Trust Anchor may be stored along with the Trust
    Anchor certificate or public key. The Trust Anchor fingerprint
    can be part of Trust Anchor format. A device can use the
    fingerprint to uniquely identify a Trust Anchor.
    The Trust Anchor private key owner can sign certificates of other
    public keys, which conveys trust about those keys to the device.
    A certificate signed by the Trust Anchor communicates that the
    private key holder of the signed certificate is trusted by the
    Trust Anchor holder, and can therefore be trusted by the device.
    Trust Anchors in a device may be updated by an authorized party
    when a Trust Anchor should be deprecated or a new Trust Anchor
    should be added."

**Comment by dthaler** [comment]
All good except one sentence is confusing:
"The Trust Anchor fingerprint can be part of Trust Anchor format."
What is "Trust Anchor format"?

**Comment by mingpeiwk** [comment]
If it is a fingerprint, shall we define what fingerprint it should be and how it is represented (SHA1 or SHA2 hash of a certificate or some more)? When it is a public key, what structure should a TEE support? A Trust Anchor can consist of a public key and fingerprint (of the certificate). I was thinking of a structure we may cite from others. RFC6024 describes requirement for a Trust Anchor Format. Maybe we loosely leave the trust anchor content structure to TEE about how it will interpret a "fingerprint", a "public key", and their combined use?

By this, I will just remove that line "The Trust Anchor fingerprint can be part of Trust Anchor format.". The prior sentence has described it will be stored along with other data. The interpretation and content of a fingerprint, e.g. fingerprint algorithm, will be left to TEE.

**Comment by dthaler** [comment]
Verified fixed in draft -02 and later
