### ISSUE TITLE
Algorithm Agility and Longer Key Sizes

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#4]
This issue was raised by David Wheeler on slide #12 of https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-recommendations-for-teep-support-of-intel-sgx-technology-02

**Comment by hannestschofenig** [comment]
Architecturally we will support this functionality. Text to be added to the document.

**Comment by dthaler** [comment]
Added in section 8 in draft-ietf-teep-architecture-01
