### ISSUE TITLE
Option to not use secure boot

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#5]
David Wheeler raised this issue in slide 8 of https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-recommendations-for-teep-support-of-intel-sgx-technology-02 since SGX does not depend on secure boot.

**Comment by dthaler** [comment]
At the meeting, I believe there was tentative consensus on this point.  Minutes were posted and there have been no objections (or subsequent discussion on this point) on the list.

**Comment by hannestschofenig** [comment]
Architecture should be agnostic to secure boot. 

Description of the trusted firmware (Arm) & microcode (SGX) concepts useful.

**Comment by dthaler** [comment]
In addition, Henk argued at IETF 102 that "secure boot" is an obsolete concept.   The document could use "Measured Boot" instead.  (See https://forums.juniper.net/t5/Security/What-s-the-Difference-between-Secure-Boot-and-Measured-Boot/ba-p/281251 or various other links for an explanation of the difference, if you want to know.)

**Comment by dthaler** [comment]
draft-ietf-teep-architecture-01 removes secure boot text
