### ISSUE TITLE
Session based TA Provisioning and Management Architecture

### ISSUE THREAD

**Issue by cyberphone** [ietf-teep/architecture#52]
As the architecture seems to still be under consideration I take the liberty suggesting an alternative to the current static TEE attestation scheme.  This is based on experiences gathered at the Office of the CTO of RSA Security and in TCG.  The idea is simply that an attestation challenge-response sequence in addition to transferring trust information, also creates a "session" and an associated shared session key.  This enables a bunch of potentially useful features:

- High-level human-readable MAC-protected API talking binary to primitive (_resource constrained_) TEEs
- Offloading JSON and BASE64 encoding/decoding, Networking and UI to the REE level
- Makes the TEE part _independent of protocol language_ (XML/JSON/CBOR)
- Encryption using derived session key
- API and response aggregation/pipe-lining
- User interaction inside of the protocol
- Provisioning of complex structures in a step-wise fashion
- Virtual namespace eliminates need for explicit key IDs
- Atomic multi-phase provisioning
- Credential management with issuer isolation

This has been successfully applied to a Secure Key Store/Provisioning Protocol powering a universal "Wallet" coined [Saturn](https://cyberphone.github.io/doc/saturn/). 

"TEE": https://cyberphone.github.io/doc/security/sks-api-arch.pdf
Protocol: https://cyberphone.github.io/doc/security/keygen2.html#Sample_Run
IPR declaration: https://priorart.ip.com/IPCOM/000215433

All features above may not be meaningful in a TEEP scenario.

**Disclaimer**: *the scheme above has not been subjected to a peer review*

**Comment by cyberphone** [comment]
A more illustrative example:
![teep](https://user-images.githubusercontent.com/8044211/55213853-f5401b00-51f4-11e9-9e5a-4e97c8ceec6e.png)
SKS = TEE

**Comment by cyberphone** [comment]
This 5 year old picture shows how you can make better use of silicon through a three-level security architecture.  The system is currently only available as a software emulator which has been used to verify the concept:
![threelevel](https://user-images.githubusercontent.com/8044211/56785133-11cf7300-67f4-11e9-85be-805f488099fc.png)

**Comment by cyberphone** [comment]
### Unified TEE Management API

Converting OTrP into a session based system built on top of a unified TEE management API would indeed require massive changes since more data would probably be tied to the initial session creation request.  To cope with multiple sessions there must also be a non-secret *Session ID*.  Here is an example of a protected API which at the protocol level can be expressed in any suitable format (JSON, CBOR, XML, ASN.1, etc.) before being translated into binary for the TEE:

**DoSomething** (*Session ID*, *Unencrypted Parameter*, *Encrypted Parameter*, *MAC*)

Notes:

*Encrypted Parameter* only holds the actual ciphertext (binary) since keys, algorithms etc. are defined during the session creation.  Data is encrypted using a symmetric key derived from the shared session key.

*MAC* holds the binary result of a HMAC operation (using the shared session key) over the **Method name**, **Session ID**, **Parameters** and a **Sequence counter**.  The latter is incremented for each API call to enable verification of API call sequence order. 

A session terminates with something like

**Finalize** (*Session ID*, *Nonce*, *MAC*)

returning a success attestation (or failure) using the shared session key.  Only if successful the preceding API calls should become in effect.  If time out or other errors occur, *rollback should be automatically performed*.

In KeyGen2 it turned out to be possible *aggregating* API calls at the protocol level but that might not be applicable to TEEP.

**Comment by cyberphone** [comment]
After 2 months without a single comment it seems that this is an invalid request or maybe there's another problem like:
![Challenges-facing-transformation-too-busy-wheel](https://user-images.githubusercontent.com/8044211/58684748-96745a80-8379-11e9-8fb1-3d52bc603d6b.png)

**Comment by dmwheel1** [comment]
Anders,
From my perspective, the information provided appeared to be a complete solution, and was difficult to identify where or how to apply it without completely throwing away the entire TEEP proposal. Personally, the potential for IP rights kept me from digging in deeper.

Perhaps, if you can provide more detail on specifics regarding what should change, or directly apply it to the specification (identify specific sections), it is easier for us to comprehend and fold into the work.

The picture is very apt, I think 😊
Is the cart for transporting items, or is it for plowing a field? Clear intentions and purpose are important!

Dave W.

**Comment by cyberphone** [comment]
@dmwheel1 
>  From my perspective, the information provided appeared to be a complete solution, and was difficult to identify where or how to apply it without completely throwing away the entire TEEP proposal. 

The [architecture](https://tools.ietf.org/html/draft-ietf-teep-architecture-02) would probably be more or less intact while the [protocol](https://tools.ietf.org/html/draft-ietf-teep-opentrustprotocol-03) would be considerably revised.  However, the "methods" like `InstallTA` are still completely relevant.

*The main work is probably getting the code back in shape*.

> Personally, the potential for IP rights kept me from digging in deeper.

I understand.  I can of course only show that I have filed defensive (prior art) publications on the core mechanisms:  https://cyberphone.github.io/doc/defensive-publications/Efficient-Provisioning-of-Complex-Structures-Over-Unsecured-Channels.pdf#page=4

 What other entities may have patented is more than I know.

The most "novel" part is probably creating an attestation and a shared session key (using ECDH) *in a single step* making subsequent operations using the session key effectively "inherit" the attestation. 

> Perhaps, if you can provide more detail on specifics regarding what should change, or directly apply it to the specification (identify specific sections), it is easier for us to comprehend and fold into the work.

*IF* there is interest in creating a binary TEE Management API on the same level as TPM, PKCS11, ISO7816, etc. I'm willing to create some kind of specification.
 
> The picture is very apt, I think 😊
> Is the cart for transporting items, or is it for plowing a field? Clear intentions and purpose are important!

It must be a truly ingenious design, it appears to do both 😊

**Comment by cyberphone** [comment]
https://cyberphone.github.io/doc/research/unified-tee-management-api.pdf

**Comment by dthaler** [comment]
First, we have a goal to retain backwards compatibility for GlobalPlatform.  (The TEEP charter says "The group will maintain a close relationship with the IETF SUIT working group, GlobalPlatform, Trusted Computing Group, and other relevant standards groups to ensure interoperability, compatibility, and proper use of existing TEE-relevant application layer interfaces." and GlobalPlatform folks have stated on the list that they want interop with the current version being deployed.)

Second, as an individual, I believe that the JSON (or even CBOR) approach is easier to extend over time.  That's because the component outside the TEE (called the Broker in the arch doc) does not need to change, and JSON is inherently extensible due to its self-describing nature.  In contrast, a binary API cannot add new parameters without changing the API signature.   As such, in my prototype implementation, a JSON or CBOR encoding would be much more convenient than a binary API.   In theory a binary API could be used inside the OTrP Agent inside the TEE, the important bit being that it's used after the JSON/CBOR payload signature/encryption is verified inside the TEE.   However, I'm not sure yet what the value would be.

BTW, write-up proposals like the PDF would be easier to deal with in IETF process if it were in Internet Draft format, if there is further interest in discussing in a meeting.

**Comment by cyberphone** [comment]
@dthaler @hannestschofenig @dmwheel1 I probably lack some pieces of information regarding TEE management but let me briefly (well...) comment on the above:

- _Compatibility with GlobalPlatform is (AFAICT) not possible without severely constraining the TEEP work_.  The result of TEEP's work will (at best) be "similar".

- I don't see that there would be a need verifying/parsing JSON data within the TEE.  If there is, the whole idea would indeed be of no value.   That it is simple to use JSON is true but in most systems there is some kind of API you eventually have to talk to.  This API sets the limit for the rest.  I guess you want to get away from this mapping using a pure JSON API?  For SGX that would work fine, for other and more limited systems, maybe not.  _This proposal effectively targets the silicon level as well_.

- The PDF _is just a presentation_ showing how I envisioned that OTrP would change if a session based (stateful) architecture would be used.  A possible "upgrade" would require major thinking by the core team!

Anyway, this requirement/wish/whatever stems from the TA-side where there already are established precedents (smart card provisioning) using shared keys serving as indirect attestations.  This enables you to _securely deploy arbitrary data structures in a stepwise fashion_.

The scheme used in SKS (Secure Key Store) takes this to another level by making the entire session "atomic".  This permits things like secure replacements of virtual payment cards, like implemented in [Saturn](https://cyberphone.github.io/doc/saturn/saturn-authorization.pdf).

Implementing SKS as a TA using the current OTrP/TEEP architecture would require doing everything from scratch since it cannot reuse anything from the TA management system.

**Comment by mingpeiwk** [comment]
Thanks Anders for your proposals, and the example how you would like the protocol API look. I am still in an opinion of use standard RFC JOSE for signing instead of using our own MAC scheme where we deal with how data to be signed is concatenated, and where a MAC algorithm is carried etc.

On use of JSON or CBOR, the "request" data from TAM will be processed by a TEE side TEEP module in a device. The "response" from TEE side will be processed by a TAM. JSON / CBOR is pretty lightweight enough for the system in the two sides, I think. It is also very developer friendly.

Thanks again for the suggestion of an alternative to do it, and it is a beneficial discussion.

**Comment by cyberphone** [comment]
Hi @mingpeiwk It is really the *Session Concept* that is the most important part of this proposal.  It could even use JWS (HS256) and JWE (A256GCM) in case binary is considered too awkward.

Sample binary:
https://github.com/cyberphone/openkeystore/blob/b762949fe45579a391ed1772a0e890aa83840f5b/library/test/org/webpki/sks/SKSReferenceImplementation.java#L3122

This is BTW like a continuation of [KEYPROV](https://datatracker.ietf.org/wg/keyprov/about/) 😁

Good luck anyway!  Personally I will stick to the session concept because static attestations can't deliver what my scheme requires (secure multi-phase atomic provisioning).

**Comment by mingpeiwk** [comment]
Thanks Anders. I know. The session concept doesn't look to me that TEEP has a strong use case. TA management is the core task. Key provisioning and management tend to have stronger session dependency, for example, [KEYPROV](https://datatracker.ietf.org/wg/keyprov/about/) DSKPP multi-phase provisioning.

**Comment by cyberphone** [comment]
Agreed.

However, when you in *retrospect* look into all the JSON/CBOR *duplication* you are about to do (including EAT), you *may* regret not considering this somewhat bold step.  Although maybe not that important, a session based TA management protocol becomes much "cleaner" as shown in the [PDF](https://cyberphone.github.io/doc/research/unified-tee-management-api.pdf).

If Dave's code was Open Sourced, I would even consider making an alternative version for SGX.
@hannestschofenig @dmwheel1 @dthaler @mingpeiwk 

Finishing here.

**Comment by cyberphone** [comment]
@dthaler Oops, the SGX code *is* open sourced. Will look into this.
