### ISSUE TITLE
Introduction, pp.4,6: regular/normal/typical operating system 

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#54]
Similar to issue #53, the use term for the (de-facto) Rich Execution Environment is used inconsistently - either "regular", or "normal", or "typical" (p.6) operating system.

Suggestion: adopt same terminology throughout the document.

**Comment by mingpeiwk** [comment]
Agreed, thanks, will update the doc.

**Comment by dthaler** [comment]
See proposed text in #71
