### ISSUE TITLE
Introduction, pp.4, 5: "untrusted application" vs "client application"

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#55]
Terms "untrusted application and "client application" are used interchangeably:
Compare:

"An application component running inside a TEE is referred to as a Trusted Application (TA), while a normal application running in the regular operating system is referred to as an Untrusted Application (UA).
"
AND
"
Client Application: An application running in a Rich Execution Environment, such as an Android, Windows, or iOS application. We sometimes refer to this as the 'Client App'.
"

Suggestion: adopt same terminology throughout the document

**Comment by dthaler** [comment]
See proposed text in https://github.com/ietf-teep/architecture/pull/71
