### ISSUE TITLE
6.2.1 Agent Distribution

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#59]
The sentence "It is important to ensure a legitimate agent is installed and used. If an agent is compromised it may drop messages and thereby introduce a denial of service." is not necessary here, since:

1. It is discussed under "Security considerations"
2. The Agent (i.e. broker) is one of the many ways of running a DOS attack on the TEE and does not need any extra highlighting; the Rich Execution Environment, considered explicitly untrustworthy, may simply block the TEEP I/O and equally perform a DOS attack.

Suggestion: remove the sentence "It is important to ensure a legitimate agent is installed and used. If an agent is compromised it may drop messages and thereby introduce a denial of service."

**Comment by dthaler** [comment]
Personally, I agree with this suggestion.

**Comment by mingpeiwk** [comment]
Done in draft-ietf-teep-architecture-03.

**Comment by dthaler** [comment]
Verified fixed in -03.
