### ISSUE TITLE
Attestation Agility

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#6]
In slide #9-11 of https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-recommendations-for-teep-support-of-intel-sgx-technology-02 David Wheeler argued that the TEEP architecture (and consequently OTrP) need to be flexible with regards to the use of different attestation mechanisms. 

At the IETF Montreal meeting it was suggested that there is a possible link to the proposed EAT work. For EAT see https://www.ietf.org/mailman/listinfo/eat

**Comment by hannestschofenig** [comment]
We agree that the architecture document should have a requirement for attestation agility. Text to be added to the architecture document.

**Comment by dthaler** [comment]
Added section 8 to draft-ietf-teep-architecture-01
