### ISSUE TITLE
Editorial update for SD full removal

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#62]
Section 7.4 has some API reference on SD APIs that should be removed in the next update.

"When a new key pair is generated for a TA-to-TAM or TA-to-SP
      communication, the keypair must be covered by an attestation,
      including "CreateSecurityDomain" response, "UpdateSecurityDomain"
      response, etc."

**Comment by dthaler** [comment]
There's still a bunch of other discussion of SDs as well.  It appears in sections 2, 5.8, 5.13, and (as Ming mentioned) 7.4.

**Comment by dthaler** [comment]
@ncamwing I believe this is now ready to be closed, as PR #72 is now merged
