### ISSUE TITLE
Clarification of the location of keys, certs, and CA certs for prototyping

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/architecture#63]
Made a slide to have a example of keys, certs and CA certs described in the draft for start prototyping the flow of TA insert and delete.

[TEEP-OTrP-key-locations-IETF-105.pdf](https://github.com/ietf-teep/architecture/files/3414909/TEEP-OTrP-key-locations-IETF-105.pdf)

**Comment by mpei1981** [comment]
Will update architecture doc to reflect a code signing verification flow. The TAM and TEE mutual validation key and certificate usage are already largely in the doc. Wording on TFW will be updated to reflect the decision that we will not require TFW, and validate the secure boot and related states that some TEE may bear.

On a related topic, we will revise the doc to reflect the trust anchors used to validate a TAM certificate and that to validate a TA application binary signing. The two trust anchor lists can be the same but conceptually they serve different purposes in processing a request to install a TA.

**Comment by mcd500** [comment]
Thanks Ming. I would like to contribute of making ascii drawing of the draft on page 19.
Probably it will be next week.
It was great to see you at IETF 105.
Is there a tool every use for drawing ascii art?
