### ISSUE TITLE
End to end security between a SP and TEE for confidential IP

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#64]
A SP may need support that a TA is only installed to devices that have assurance the confidential algorithms in a TA not get disclosed. This needs some architecture support.

TA binary itself is supported as being encrypted when it is delivered from a TAM to TEE, encrypting using a TEE's key. The question is how a SP allows a TAM to deliver its TA without disclosing it.

The confidential piece may thus becomes a "personalization data" to a TA. The TA binary can be shared with a TAM, but the confidential data remains at SP, and it should be delivered with end-to-end security to a device TEE.

**Comment by dthaler** [comment]
Per IETF 106 WG discussion, sense of room was that the following option should be done:

Agent can use a separate TAM per dependency:

- Every dependency can have its own TAM URI in the manifest file
- If a TA depends on another TA, the dependent TA might even have its own SUIT manifest
- If TAM URI for a dependency is different from the depending TA, can invoke RequestTA recursively
