### ISSUE TITLE
IoT DDoS draft issues

### ISSUE THREAD

**Issue by echallon** [ietf-teep/architecture#65]
draft-faibish-iot-ddos-usecases-00 issues

Should TEEP WG address the use cases for DDoS prevention in the architecture draft?
Use case 1: Upgradable OS less IoT devices
Use case 2: IoT devices connected to gateway
Use case 3: Smart IoT devices with rich OS

**Comment by dthaler** [comment]
Discussion at IETF 106:

- TEEP manages the TEE in a device, not the REE in a device. 
- Propose closing issues as out of scope
- This may be relevant to RATS though

I believe this issue should be closed as WG agreed no actions needed in TEEP arch doc

**Comment by tireddy2** [comment]
A compromised IoT device can be used to launch several other attacks like crypto-mining, stealing privacy-sensitive information, infecting other devices in the local network etc. All these attacks are only possible in REE.
