### ISSUE TITLE
IoT DDoS issues

### ISSUE THREAD

**Issue by echallon** [ietf-teep/architecture#66]
draft-faibish-iot-ddos-usecases-00 issues
Is TEEP the right security protocol to prevent DDoS attacks from ioT devices. Types of attacks could be random network traffic generated, reflection of network packets or amplification of legitimate network packets.

**Comment by dthaler** [comment]
TEEP manages the TEE in a device, not the REE in a device.  As such, it is not the thing that addresses such attacks conducted by REE components.   I would propose closing this issue as such.

**Comment by dthaler** [comment]
Discussion at IETF 106:

- TEEP manages the TEE in a device, not the REE in a device. 
- Propose closing issues as out of scope
- This may be relevant to RATS though

I believe this issue should be closed as WG agreed no actions needed in TEEP arch doc

**Comment by tireddy2** [comment]
Compromised devices can also be used to launch several other attacks like crypto-mining, capturing privacy-sensitive data for ransomware attacks etc. All these attacks including DDoS are possible in REE and not applicable to TEE in the device. 

I closed this issue.
