### ISSUE TITLE
IoT DDoS draft issues

### ISSUE THREAD

**Issue by echallon** [ietf-teep/architecture#67]
draft-faibish-iot-ddos-usecases-00 issues; questions
Should this draft be part of TEEP WG? 
Does TEEP WG need more detailed protocol implementation before accepting as a WG document?
Is TEEP Ready to adopt as TEEP WG document?
Perhaps if it is accepted can these usecases added to the architecture document? How?

**Comment by dthaler** [comment]
This appears to be a duplicate of #65, insofar as this issue is about the arch doc.
