### ISSUE TITLE
Single v.s Multiple TEEs: Impact on message routing

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#8]
Slide 8 and 9 in https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-teep-architecture-draft-02 raise the issue that the Agent needs to route the messages to the correct TEE. This adds extra functionality for the Agent implementation.

**Comment by dthaler** [comment]
Slide 18 of https://www.cs.helsinki.fi/group/secures/CCS-tutorial/tutorial-slides.pdf seems useful in listing several cases with multiple TEEs

**Comment by dmwheel1** [comment]
See new pull request on 1/31/2019 to address this issue

**Comment by dmwheel1** [comment]
This should be closed per the pull request that was merged. If agreement from other authors, please close this issue.

**Comment by dthaler** [comment]
Verified addressed in the document. Any additional issues can be filed as new issues.
