### ISSUE TITLE
Install TA in single pass

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-teep/architecture#9]
Dave Thaler suggested to offer an optimization that allows the installation of a TA in single pass in 
slide #7 of https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-teep-hackathon-report-03

**Comment by dthaler** [comment]
Dave Wheeler has action item to propose diagram and text for arch doc before Montreal.
Ming can do protocol spec updates as needed based on that text.
Dave Thaler can do transport spec updates as needed based on that text.

**Comment by dthaler** [comment]
Verified addressed in draft -03
